name: Ramblings of a Dev
description: Blogging about code stuff
meta_description: "Ramblings of a Dev, Blogging about code stuff"

aboutPage: false

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://mitchel.me'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://mitchel.me'
author:         'Mitchel Cabuloy'
authorTwitter:  'mixxorz'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
